from subprocess import Popen

# name generated by for loop...
epochs = [30]
batch_sizes = [1]
lrs = [1e-8, 1e-4, 1e-2]
momentums = [0.9]
vals = [0.1]
seeds = [0]
total_imageses = [10, 300, 5000]
net_sizes = [[1,128,256,512,1024],[1,16,32,64,1024]]


i=0
    
for epoch in epochs:
    for batch_size in batch_sizes:
        for lr in lrs:
            for total_images in total_imageses:
                for net_size in net_sizes:
                    i += 1
                    run_name = 'run' + str(i)
                    print(run_name)
                    command = ["python", "model.py", 
                                "-n", str(run_name),
                                "-e", str(epoch),
                                "-b", str(batch_size),
                                "-lr", str(lr),
                                "-ti", str(total_images),
                                "-ns", str(net_size[0]), str(net_size[1]), str(net_size[2]),  str(net_size[3]), str(net_size[4])]
                                # "-m", momentum,
                                # "-v", val,
                                # "-s", seed,
                                # ""]
                    p = Popen(command)
                    (output, err) = p.communicate()
    
